
package Vistas;

import java.awt.Dimension;
import controlador.Ctrl_Producto;
import DAO.ProductoDAO;
import Modelo.Producto;
import Servicio.ProductoServicio; 
import javax.swing.JOptionPane;
/**
 *
 * @author Brian Rivera
 */
public class RegistrarProducto extends javax.swing.JInternalFrame {
    private Ctrl_Producto ctrl_Producto;

    /**
     * Creates new form RegistrarProducto
     */
    public RegistrarProducto() {
       initComponents();
       this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setTitle("Registrar Producto");
        this.setSize(549, 565);
        this.ctrl_Producto = new Ctrl_Producto(new ProductoServicio(new ProductoDAO()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_proveedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_precio1 = new javax.swing.JTextField();
        jButt_Guardar = new javax.swing.JButton();
        jBut_limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Registrar Nuevo Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Registrar Nuevo Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Registrar Nuevo Producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Categoria");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_codigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_codigo.setMargin(new java.awt.Insets(5, 10, 5, 10));
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 430, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Proveedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Stock");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        txt_categoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria:", "Bebidas", "Caramelos", "Galletas" }));
        txt_categoria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 430, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre del Producto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, -1));

        txt_proveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_proveedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_proveedor.setMargin(new java.awt.Insets(5, 10, 5, 10));
        getContentPane().add(txt_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 430, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Codigo del Producto");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombre.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 430, 30));

        txt_stock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Precio Unitario");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txt_precio1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 190, 30));

        jButt_Guardar.setBackground(new java.awt.Color(0, 204, 0));
        jButt_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButt_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        jButt_Guardar.setText("Guardar");
        jButt_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButt_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 110, 40));

        jBut_limpiar.setBackground(new java.awt.Color(204, 0, 51));
        jBut_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBut_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBut_limpiar.setText("Limpiar");
        jBut_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 110, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoclaro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categoriaActionPerformed

    private void jButt_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_GuardarActionPerformed
     
        
        
        String nombre = txt_nombre.getText().trim();
        String categoria = (String) txt_categoria.getSelectedItem();
        String codigo = txt_codigo.getText().trim();
        String proveedor = txt_proveedor.getText().trim();
        String precioStr = txt_precio1.getText().trim();
        String stockStr = txt_stock.getText().trim();

        if (nombre.isEmpty() || categoria.equals("Seleccione categoria:") || codigo.isEmpty() ||
            proveedor.isEmpty() || precioStr.isEmpty() || stockStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double precio = Double.parseDouble(precioStr);
            int stock = Integer.parseInt(stockStr);

            Producto producto = new Producto();
            producto.setNombre(nombre);
            producto.setCategoria(categoria);
            producto.setCodigo(codigo);
            producto.setProveedor(proveedor);
            producto.setPrecioUnitario(precio);
            producto.setStock(stock);

            boolean guardado = ctrl_Producto.guardarProducto(producto);
            if (guardado) {
                JOptionPane.showMessageDialog(null, "Producto registrado exitosamente.");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar el producto.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores numéricos válidos para precio y stock.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButt_GuardarActionPerformed
private void limpiarCampos() {
    txt_nombre.setText("");
    txt_categoria.setSelectedIndex(0); // O el índice que corresponda a "Seleccione categoria:"
    txt_codigo.setText("");
    txt_proveedor.setText("");
    txt_precio1.setText("");
    txt_stock.setText("");
}

    private void jBut_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_limpiarActionPerformed
    limpiarCampos();
        
        
    }//GEN-LAST:event_jBut_limpiarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_limpiar;
    private javax.swing.JButton jButt_Guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> txt_categoria;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio1;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}

